[ILLIMITY]
account_illimity="fabio.capocasale.ext@illimity.com"
password_illimity="Dkf58ExYFayFtuV"
maven_access_token="zuf4xya4dkjwkojfscxdez2qdu4zjteu6y6b2ch3vr465dozbcba"
account_be_tse="f.capocasale@be-tse.it"
password_be_tse="Amoremio141119"
azure_token="tpqusilucld3pdljmmablhqc7ohijum6bgryzpqzrs46lilvmfaq"
subscription_key_platform="972940f89c42adbf19c96f4c3965f183e99b3559f90a75438826da08561840f7"



